### PR TITLE
C++ Overlays right side is cut off.

### PR DESCRIPTION
**Pull request by RutOf**
I am inserting an overlay div with width 100%, but the overlay div is not rendered completely. For some reason, it looks as if it has moved rightward.

```css
.overlay {
  position: fixed;
  left: 0;
  top: 0;
  width: 100%;
  height: 100%;
  z-index: 1000000;
  background-color: rgba(255, 255, 255, 0.85);
  -webkit-transition: opacity .2s linear;
  transition: opacity .2s linear;
  padding: 20px;
}
```

### CODE REVIEW

**Comment by Fnoberz** [comment]
That's why when you set the width to 100% (relative to the window), the padding will go outside the window.

**Comment by Fnoberz** [comment]
If you wish to fit the size, with the padding, you should not set any width property.

**Comment by Fnoberz** [comment]
But, in your case, your string is a bunch of "A"s, which will affect the property listed above. In this case, you would need to set the width to 40px shorter than the window width. (Because the padding on the left and right are 20px respectively, 20 + 20 = 40)

**Comment by Fnoberz** [comment]
```css
document.getElementsByTagName("div")[0].style.width = window.innerWidth - 40 + "px"; 
```

**Comment by Fnoberz** [comment]
Apart from that, if you want the "A"s to move to the next line, use this css property:

**Comment by Fnoberz** [comment]
```css
word-wrap: break-word;
```

**Comment by Fnoberz** [comment]
Otherwise, use one of the following two css properties:

```css
overflow: hidden;
white-space: nowrap;
```

**Comment by RutOf** [comment]
OH THANKS YOU

**Pull request merged**
